# fly.toml app configuration file generated for stremio-addon-titlovi on 2025-06-01T19:13:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stremio-addon-titlovi'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 5555
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
